import { Inter, Kanit } from "next/font/google";
import "./styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

const kanit = Kanit({ subsets: ["latin"], weight: ["400"] });
import Header from "./components/header";
import { Footer } from "./components/footer";

export const metadata = {
  title: "Chirayu's portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header kanitClassName={kanit.className}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
